insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '4700', 'Duncraig Primary', '01', 'Joondalup', 'PRIMARY', 'Y', null);
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '4800', 'Carine Snr High', '02', 'Stirling', 'HIGH', 'Y', null);
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '4900', 'St. Stevens Primary', '01', 'Joondalup', 'PRIMARY', 'N', 'CATHOLIC');
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '5000', 'Scarborough High', '02', 'Stirling', 'HIGH', 'Y', null);
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '5100', 'Kununurra Remote High', '20', 'Kimberley', 'HIGH', 'Y', null);
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '5200', 'Ballajura High', '15', 'Wanneroo', 'High', null, 'Rastafari');
insert into SCHOOL (REF_ID,LOCAL_ID,SCHOOL_NAME,DISTRICT_ID,DISTRICT_NAME,SCHOOL_TYPE,GOVERNMENT_SCHOOL,RELIGIOUS_AFFILIATION) 
      values (null, '5300', 'Warburton Remote School', '18', 'Interior WA', null, null, null);

insert into STUDENT (SIF_REFID,LOCAL_ID,YOUNG_CARER,HAS_DISABLITY,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,GENDER,LANGAUGE_AT_HOME,DOB,STREET_NAME_AND_NO,CITY,POST_CODE,STATE,PHONE_NUMBER,PHONE_TYPE)
      values ('9AB12ACD00EDD2355EBF78FF43345EFB','4552287009','N','N','Peter',null,'Ledger',null,'M','ENG',null,'7 Poynter Rd.','Duncraig','6023','WA',null,null)
insert into STUDENT (SIF_REFID,LOCAL_ID,YOUNG_CARER,HAS_DISABLITY,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,GENDER,LANGAUGE_AT_HOME,DOB,STREET_NAME_AND_NO,CITY,POST_CODE,STATE,PHONE_NUMBER,PHONE_TYPE)
      values ('E3412ACBB0985EA3412BCD34EE5609AE','5907837123','N','N','Denis',null,'White',null,'M','GER',null,'8/82 Colin Rd','Scarborough','6018','WA','08 9287 9314','HOME')
insert into STUDENT (SIF_REFID,LOCAL_ID,YOUNG_CARER,HAS_DISABLITY,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,GENDER,LANGAUGE_AT_HOME,DOB,STREET_NAME_AND_NO,CITY,POST_CODE,STATE,PHONE_NUMBER,PHONE_TYPE)
      values ('A43290EEDFA3405EF643AA6120EE7622','1207899125','Y','N','Hannah','Mary','Peterson','Mrs','F',null,null,'12 Drake Blvd','Wembley','6022','WA','0404923981','MOB')
insert into STUDENT (SIF_REFID,LOCAL_ID,YOUNG_CARER,HAS_DISABLITY,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,GENDER,LANGAUGE_AT_HOME,DOB,STREET_NAME_AND_NO,CITY,POST_CODE,STATE,PHONE_NUMBER,PHONE_TYPE)
      values ('E10973EFA7832BBC53ED18561EA9E312','7239893945',null,'Y','Ben',null,'Noel','Mr',null,'ENG',null,'102 Stitling Hwy','Nedlands','6009','WA',null,null)
insert into STUDENT (SIF_REFID,LOCAL_ID,YOUNG_CARER,HAS_DISABLITY,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,GENDER,LANGAUGE_AT_HOME,DOB,STREET_NAME_AND_NO,CITY,POST_CODE,STATE,PHONE_NUMBER,PHONE_TYPE)
      values ('E0927654295732EADE34439CB5328B23','1233493989',null,null,'Jessica',null,'Richmond',null,null,'ENG',null,'55 Lowndes Rd','Melboune','3000','VIC','03 6755 2328',null)
insert into STUDENT (SIF_REFID,LOCAL_ID,YOUNG_CARER,HAS_DISABLITY,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,GENDER,LANGAUGE_AT_HOME,DOB,STREET_NAME_AND_NO,CITY,POST_CODE,STATE,PHONE_NUMBER,PHONE_TYPE)
      values ('0374DBDB343AE97546F677B421A095F4','3945538525','N',null,'Daniel',null,'Vanderheeg',null,null,'ENG',null,'7 Newberry Close','Hawthorn','3122','VIC','03 1276 2895','HOME')
insert into STUDENT (SIF_REFID,LOCAL_ID,YOUNG_CARER,HAS_DISABLITY,FIRST_NAME,MIDDLE_NAME,LAST_NAME,TITLE,GENDER,LANGAUGE_AT_HOME,DOB,STREET_NAME_AND_NO,CITY,POST_CODE,STATE,PHONE_NUMBER,PHONE_TYPE)
      values ('74E208669C75B58D4E5E88997F66D67F','1278234008','N','N','Greg','John','Power',null,'M','ENG',null,'11 Joondalup Drive','Joondalup','6043',null,null,null)


